### ISSUE TITLE
Building python bindings on Windows -> linker errors

### ISSUE THREAD

**Issue by paulgrassler** [bet4it/udbserver#13]
Hey,
I have been trying to build the python bindings for the udbserver on Windows for days now but it seems I am still not completely understanding what goes wrong. :/ At this point I am really frustrated and looking desperately for any help I can get. I know this was originally built for Linux but from what I have seen some people seem to have it working on Windows. Would be really great if any of you could me help me here given that you know where I am going wrong.

When I initially tried building I got a whole bunch of linker errors looking like this:

`udbserver.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetAttr`
`udbserver.obj : error LNK2001: unresolved external symbol __imp___Py_NoneStruct`
`udbserver.obj : error LNK2001: unresolved external symbol __imp__Py_Initialize`
`udbserver.obj : error LNK2001: unresolved external symbol __imp__PyModule_Create2`
`udbserver.obj : error LNK2001: unresolved external symbol _udbserver`
`udbserver.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsVoidPtr`
`udbserver.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromString`
`udbserver.obj : error LNK2001: unresolved external symbol __imp__PyArg_ParseTuple`
`build\lib.win32-cpython-311\udbserver.cp311-win_amd64.pyd : fatal error LNK1120: 8 unresolved externals`

Since then I came to the conclusions that I am supposed to use the 32-bit python version since this eliminates all of the unresolved python symbols errors. However, even when using the 32-bit version I am still getting one of the linker error:

`udbserver.obj : error LNK2001: unresolved external symbol _udbserver`
`build\lib.win32-cpython-311\udbserver.cp311-win32.pyd : fatal error LNK1120: 1 unresolved externals`

From my limited knowledge I figured this seems like '_udbserver' is a symbol defined in the 32-bit way but the udbserver libraries are built in 64-bit which means the symbol is likely defined without the underscore (this is a similar issue I think: https://stackoverflow.com/questions/63750020/unresolved-external-symbol-error-when-linking-a-cython-extension-against-a-c-l). Lately I have been trying to find a way to somehow get 32-bit versions of the udbserver libraries in the hopes that this would fix my issues but I have not really found a way to do this and additionally I am not even sure if this is the correct way to go about this.

I have also tried implementing the changes of the pull request #11 with regards to the 'setup.py' file. At first I got the following error:

`LINK : fatal error LNK1181: cannot open input file 'unicorn.lib'`

I then manually added the 'unicorn.lib' file to the working directory which ended up getting the same bunch of linking errors I initially got.

I am sure there is something that goes over my head here but regardless of how much I try I can not figure it out. So if you can spend any time at all helping me here I would be really really grateful. Completely stuck at the moment.

**Comment by mglinski** [comment]
Go back to building against 64 bit python. The issue you are having is that you are, for some reason, not including the windows python module libraries in the linker search path. Those missing implementation references are python binary library methods, which the linker can’t find in any of the library files that it was able to locate.

This likely means that the directory containing your win64 compatible python binary library files is not in the path array being checked by the linked.

locate those files and ensure the linker is also looking in that folder.

**Comment by paulgrassler** [comment]
Hmm, I thought about that but as you can see in the setup output, various python folders are included in the include and library paths. I will try to reinstall python.

What got me to try the 32-bit python version in the first place was that I often see 'win32' mentioned in the attached output. That is why I thought the whole project is supposed to be built in 32-bit and after the linker errors disappeared I felt somewhat validated. Seems to have been a bunch of misinterpretations then.

Here is what I get as output in the console after running 'setup.py install':

[setup output.txt](https://github.com/bet4it/udbserver/files/12278968/setup.output.txt)

**Comment by mglinski** [comment]
win32 in this case is the name of the binary api.

I believe the issue 100% is some python windows dev binary libraries for python not installed or not located in the correct folder. 

Try installing a windows python venv using something like Anaconda/miniconda and you might see an option to include windows dev library files. Then try building in that env.

Also make sure you have the Windows SDK installed and in your path.

**Comment by bet4it** [comment]
Do you really need to build it by yourself? You could just download the compiled binary from https://github.com/wtdcode/udbserver/suites/13288518790/artifacts/725248477.

**Comment by paulgrassler** [comment]
Oh, I was not aware of a compiled binary. That looks like it could help me avoid a lot of issues haha. I will try some examples with this. Thank you very much! And thank you @mglinski for your help so far. Was not able to solve the building issues yet. After reinstalling python/anaconda and creating an environment I get new unresolved symbol errors which look more like Windows SDK symbols. However paths to the include and library files of the SDK are included. Well, hopefully the compiled binary works and I will not have to deal with this issues but for completeness sake I will include the output file again.

[setup_output2.txt](https://github.com/bet4it/udbserver/files/12289628/setup_output2.txt)
