### ISSUE TITLE
找不到unicorn-engine

### ISSUE THREAD

**Issue by heckerstone** [bet4it/udbserver#2]
![image](https://user-images.githubusercontent.com/12561095/166845061-a7d85b48-f2b7-4523-99c4-40ef5f522171.png)

**Comment by bet4it** [comment]
You should enable `crates.listPreReleases` in the `crates` extension.

By the way, use `udbserver` on Windows is not tested.

**Comment by heckerstone** [comment]
thanks a lot i will try on the linux
