### ISSUE TITLE
Example panicking due to UnexpectedEof error

### ISSUE THREAD

**Issue by dmell** [bet4it/udbserver#9]
Hello,

Thank you very much for open sourcing this project, which I believe has the potential to radically improve the emulation experience with Unicorn. I followed all the provided steps to compile it (with the exception of removing `"use_system_unicorn"` from `Cargo.toml`, because I wanted a fresh installation). Unfortunately, when trying to connect to the example, it crashes as you can see below.

Steps to reproduce:
- install `udbserver` without using the local installation of Unicorn
- `RUST_BACKTRACE=1 cargo run --example server`
- on another terminal, run `gdb` and then `target remote :1234`

On the first terminal, I see the following:
```
$ RUST_BACKTRACE=1 cargo run --example server
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/server`
Waiting for a GDB connection on "127.0.0.1:1234"...
Debugger connected from 127.0.0.1:37154
thread 'main' panicked at 'Failed to start udbserver: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/lib.rs:46:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1035:23
   4: udbserver::udbserver::{{closure}}
             at ./src/lib.rs:46:13
   5: unicorn_engine::ffi::code_hook_proxy
             at /home/damiano/.cargo/registry/src/github.com-1ecc6299db9ec823/unicorn-engine-2.0.0-rc7/bindings/rust/src/ffi.rs:137:5
   6: helper_uc_tracecode
             at /home/damiano/.cargo/registry/src/github.com-1ecc6299db9ec823/unicorn-engine-2.0.0-rc7/uc.c:1718:14
   7: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    929611 abort (core dumped)  RUST_BACKTRACE=1 cargo run --example server
```

In gdb instead I get this:
```
$ target remote :1234
Remote debugging using :1234
warning: while parsing target description (at line 3): Target description specified unknown architecture "arm"
warning: Could not load XML target description; ignoring
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
Truncated register 16 in remote 'g' packet
```

Am I doing anything wrong? I successfully reproduced the same issue following these steps in a VM with a fresh Linux installation, but let me know if I can provide anything further to help you debug this.

Thanks!

**Comment by bet4it** [comment]
You need to use `gdb-multiarch` rather than `gdb`.

**Comment by dmell** [comment]
Thank you! Perhaps this is worth mentioning in the README, so that folks avoid stumbling upon the same issue?

**Comment by bet4it** [comment]
You are right! I will add it later.

**Comment by gwiede** [comment]
PLEASE update the README about this, as I just spent a couple hours trying to track down what was wrong until I saw this.

Really appreciate all the hard work, thanks, this hugely improves Unicorn's usability!  I might even be in a position to help contribute at some point.

**Comment by bet4it** [comment]
@gwiede Sorry for the delay!
